ALTER TABLE `core_member_info`
	CHANGE COLUMN `IS_FROZEN` `MEMBER_STATE` BIT(1) NULL DEFAULT b'0' COMMENT '成员状态' AFTER `PASSWORD`;

ALTER TABLE `core_dic_info_detail`
	ALTER `DETAIL_NAME` DROP DEFAULT,
	ALTER `DETAIL_CODE` DROP DEFAULT,
	ALTER `DETAIL_VALUE` DROP DEFAULT,
	ALTER `DETAIL_LEVEL` DROP DEFAULT;
ALTER TABLE `core_dic_info_detail`
	CHANGE COLUMN `DETAIL_NAME` `DETAIL_NAME` VARCHAR(100) NULL COMMENT '详细类型名称' AFTER `DIC_ID`,
	CHANGE COLUMN `DETAIL_CODE` `DETAIL_CODE` VARCHAR(50) NULL AFTER `DETAIL_NAME`,
	CHANGE COLUMN `DETAIL_VALUE` `DETAIL_VALUE` VARCHAR(50) NULL COMMENT '值' AFTER `DETAIL_CODE`,
	CHANGE COLUMN `DETAIL_LEVEL` `DETAIL_LEVEL` INT(11) NULL COMMENT '顺序' AFTER `DETAIL_VALUE`;

ALTER TABLE `core_dic_info_detail`
	CHANGE COLUMN `DETAIL_LEVEL` `DETAIL_LEVEL` INT(11) NOT NULL DEFAULT '0' COMMENT '顺序' AFTER `DETAIL_VALUE`;
