ALTER TABLE `core_tree_info`
	ADD COLUMN `CAN_UPDATE` BIT NOT NULL DEFAULT b'1' COMMENT '是否能修改' AFTER `TREE_TYPE`,
	ADD COLUMN `CAN_DELETE` BIT NOT NULL DEFAULT b'1' COMMENT '是否能删除' AFTER `CAN_UPDATE`;
