CREATE TABLE `core_tree_info` (
	`TREE_ID` CHAR(36) NOT NULL,
	`PARENT_ID` CHAR(36) NULL DEFAULT NULL COMMENT '父id',
	`TREE_NAME` VARCHAR(1000) NULL DEFAULT NULL COMMENT '树名称',
	`TREE_LEFT` INT(10) NOT NULL COMMENT '树左值',
	`TREE_RIGHT` INT(10) NOT NULL COMMENT '树右值',
	`TREE_TYPE` INT(10) NOT NULL COMMENT '树类型',
	PRIMARY KEY (`TREE_ID`)
)
COMMENT='树形结构表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
